// apps/react-app/src/app/app.tsx
import React from 'react';

import '@smart-elements';
import '@nx-example/ui';
import './app.scss';

export const App = () => {
  const title = 'react-app';
  return (
    <div>
      <div style={{ textAlign: 'center' }}>
        <ui-greeting title={title}></ui-greeting>
      </div>
      <p>
        This is a React app built with <a href="https://nx.dev">Nx</a>.
      </p>
      <h2>Smart ListBox Web Component</h2>
      <smart-list-box>
        <smart-list-item value="Bulgaria">Bulgaria</smart-list-item>
        <smart-list-item value="United Kingdom">United Kingdom</smart-list-item>
        <smart-list-item value="United States">United States</smart-list-item>
      </smart-list-box>
    </div>
  );
};

export default App;

// apps/angular-app/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'nx-example-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-app';
}

<h1>Welcome!</h1>

<div style="text-align:center">
  <ui-greeting [title]="title"></ui-greeting>
</div>

<p>This is an Angular app built with <a href="https://nx.dev">Nx</a>.</p>

<h2>Smart ListBox Web Component</h2>
<smart-list-box>
  <smart-list-item value="Bulgaria">Bulgaria</smart-list-item>
  <smart-list-item value="United Kingdom">United Kingdom</smart-list-item>
  <smart-list-item value="United States">United States</smart-list-item>
</smart-list-box>

<div>nonsense</div>

<div class="messages-container">
  <div class="message" *ngFor="let message of (messages$ | async); trackBy: trackByFn">
    {{ message.user }} : <span [style.color]="message.color">{{ message.message }}</span>
  </div>
</div>
<div class="input-section">
  <input [style.color]="color" type="text" [(ngModel)]="currentMessage" (keyup.enter)="sendMessage()" />
  <input type="text" [(ngModel)]="user" />
  <input type="color" [(ngModel)]="color" />
</div>
